### PR TITLE
Secret pre ship

### PR DESCRIPTION
**Pull request by wudifeixue**
1. secret backend API
2. secret frontend
3. socket data change from getPure to get
4. fixed a typo in router
5. clean up dev work

### CODE REVIEW

**Comment by wudifeixue** [comment]
@simon300000 急急急，2周了呀Simon，快来review下吧，好想用新功能233

**Comment by simon300000** [comment]
我有个考试😢

**Comment by wudifeixue** [comment]
草，那你先考，别彻底忘了这个就行

**Comment by simon300000** [comment]
9c39556e-aaee-11e4-9caf-bd06630b03d2 png

**Pull request merged**
